//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTI619_Lab5.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminOption
    {
        public int Id { get; set; }
        public int MinPasswordLength { get; set; }
        public bool IsUpperCaseCharacterRequired { get; set; }
        public bool IsLowerCaseCharacterRequired { get; set; }
        public bool IsNumberRequired { get; set; }
        public bool IsSpecialCharacterRequired { get; set; }
        public int MaxLoginAttempt { get; set; }
        public int TimeoutAfterMaxLoginReachedInMinutes { get; set; }
        public int PasswordExpirationDurationInDays { get; set; }
        public int NumberOfPasswordToKeepInHistory { get; set; }
    }
}
